// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerialErrors } from "./SerialErrors";

export interface SerialError { error_type: SerialErrors, message: string, }